home/urls.py
from django.urls import path
from .views import * 

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    
    path('chamados/', chamados_view, name='chamados_view'),
    path('chamado/edita_chamado/<int:chamado_id>/', edita_chamado, name='edita_chamado'),
    path('chamado/deleta_chamado/<int:chamado_id>/', deleta_chamado, name='deleta_chamado'),
    path('chamado/concluir_chamado/<int:chamado_id>/', concluir_chamado, name='concluir_chamado'),
    path('chamado/reabrir_chamado/<int:chamado_id>/', reabrir_chamado, name='reabrir_chamado'),
    path('chamados/abrir_chamado/', abrir_chamado, name='abrir_chamado'),
   
    path('funcionarios/', funcionarios_view, name='funcionarios'),
    path('funcionarios/edita_funcionario/<int:funcionario_id>/', edita_funcionario, name="edita_funcionario"),
    path('funcionarios/exclui_funcionario/<int:funcionario_id>/', exclui_funcionario, name="exclui_funcionario"),
    path('funcionarios/adiciona_funcionario/', adiciona_funcionario, name="adiciona_funcionario"),
    path('funcionarios/deleta_chamado_funcionario/<int:chamado_id>/', deleta_chamado_funcionario, name="deleta_chamado_funcionario"),
   
    path('estatisticas/', estatisticas_view, name='estatisticas'),

    # path('setores/', setores_view, name='setores'),
    # path('setores/adiciona_setor/', adiciona_setor, name='adiciona_setor'),
    # path('setores/edita_setor/<int:setor_id>/', edita_setor, name='edita_setor'),
    # path('setores/exclui_setor/<int:setor_id>/', exclui_setor, name='exclui_setor'),

    path('login/', login_view, name='login'),
    path("logout/", logout_view, name="logout"),
]

prefeitura/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import messages
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/forms/accounts.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs.update({
            'class': 'fadeIn second',  # Classe do CSS para o campo de username
            'placeholder': 'Login',
            'id': 'username'
        })
        
        self.fields['password'].widget.attrs.update({
            'class': 'fadeIn third',  # Classe do CSS para o campo de password
            'placeholder': ' Senha',
            'id': 'password',
        })

home/views/accounts.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from ..forms import LoginForm

def login_view(request):
    if request.method == "POST":
        loginForm = LoginForm(request, data=request.POST)

        if loginForm.is_valid():
            user = loginForm.get_user()
            if user is not None:
                login(request, user)
                return redirect('home:home')

    return render(request, 'home/accounts/accounts.html', context={'form': LoginForm})

def logout_view(request):
    logout(request)
    return redirect('home:login')

home/views/chamados.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from ..models import Chamado
from ..forms import ChamadoForm
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')
def chamados_view(request):
    nivel_usuario = request.user.perfil.funcionario.nivel
    setor_usuario = request.user.perfil.funcionario.setor
    funcionario_usuario = request.user.perfil.funcionario

    if nivel_usuario == 'funcionario':
        chamados = Chamado.objects.filter(
            Q(funcionario_abriu=funcionario_usuario) & Q(ativo=True) | 
            Q(setor=setor_usuario) & Q(ativo=True)
        ).order_by('-data_abertura')
    elif nivel_usuario == 'adm':
        chamados = Chamado.objects.filter(
            Q(funcionario_abriu__setor=setor_usuario) & Q(ativo=True) | 
            Q(setor=setor_usuario) & Q(ativo=True)
        ).order_by('-data_abertura')
    else:
        chamados = Chamado.objects.filter(ativo=True).order_by('-data_abertura')

    return render(request, 'home/chamados/chamados.html', {
        'agendamentos': chamados,
        'nivel_usuario': nivel_usuario,
        'funcionario_usuario': funcionario_usuario,
        'setor_usuario': setor_usuario
    })

@login_required(login_url='/login/')
def concluir_chamado(request, chamado_id):
    if request.method == 'POST':
        descricao = request.POST.get('descricao')
        chamado = get_object_or_404(Chamado, id=chamado_id)
        chamado.status = True
        chamado.descricao_solucao = descricao
        chamado.funcionario_fechou = request.user.perfil.funcionario
        chamado.data_fechamento = timezone.now()
        chamado.save()
    
    messages.success(request, 'Chamado concluído com sucesso.')
    return redirect('home:chamados_view')

@login_required(login_url='/login/')
def abrir_chamado(request):
    funcionario_usuario = request.user.perfil.funcionario
    if request.method == "POST":
        form = ChamadoForm(request.POST)
        if form.is_valid():
            chamado = form.save(commit=False)
            chamado.funcionario_abriu = funcionario_usuario
            chamado.save()

            messages.success(request, 'Chamado aberto com sucesso.')
            return redirect('home:chamados_view')
    else:
        form = ChamadoForm()
    return render(request, 'home/chamados/abrir_chamado.html', {'form': form,})
        
@login_required(login_url='/login/')
def reabrir_chamado(request, chamado_id):
    if request.method == 'POST':
        # descricao = request.POST.get('descricao')
        chamado = get_object_or_404(Chamado, id=chamado_id)
        chamado.status = False
        chamado.descricao_solucao = ''
        chamado.funcionario_fechou = None
        chamado.data_fechamento = None
        chamado.save()
        messages.success(request, 'O chamado foi reaberto.')
    return redirect('home:chamados_view')

@login_required(login_url='/login/')
def edita_chamado(request, chamado_id):
    funcionario_usuario = request.user.perfil.funcionario
    try:
        chamado = get_object_or_404(Chamado, pk=chamado_id)
    
        if request.method == "POST":
            form = ChamadoForm(request.POST, instance=chamado)
            if form.is_valid():
                form.save()
                messages.success(request, 'Chamado alterado com sucesso.')
                return redirect('home:chamados_view')
        else:
            form = ChamadoForm(instance=chamado)
            if chamado.funcionario_abriu == funcionario_usuario or chamado.funcionario_abriu.setor == funcionario_usuario.setor and funcionario_usuario.nivel != 'funcionario' or funcionario_usuario.nivel == 'adm_sistema':
                return render(request, 'home/chamados/editar_chamado.html', {'form': form, 'chamado': chamado, 'nivel_usuario': funcionario_usuario.nivel})
            else:
                messages.error(request, 'Você não tem permissão para acessar essa página.')
    except Chamado.DoesNotExist:
        messages.error(request, 'Esse chamado não existe ou já foi excluído.')
        
    return redirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def deleta_chamado(request, chamado_id):
    funcionario_usuario = request.user.perfil.funcionario
    if request.method == 'POST':
        if chamado.funcionario_abriu == funcionario_usuario or chamado.funcionario_abriu.setor == funcionario_usuario.setor and funcionario_usuario.nivel != 'funcionario' or funcionario_usuario.nivel == 'adm_sistema':
            chamado = get_object_or_404(Chamado, id=chamado_id)
            chamado.ativo = False
            chamado.save()
            messages.success(request, 'Chamado excluído com sucesso.')
        else:
            messages.error(request, 'Você não tem permissão para excluir esse chamado.')
    return redirect('home:chamados_view')

home/views/estatisticas.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from ..models import Chamado, Setor, Funcionario
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models import Sum
from django.db.models import Count
from calendar import monthrange
from django.contrib.auth.decorators import login_required
from datetime import datetime
import logging
import json
from django.utils.safestring import mark_safe

def get_dados_por_mes(request):    
    # Verificar o primeiro registro financeiro
    primeiro_financeiro = Chamado.objects.order_by('data_abertura').first()
    if primeiro_financeiro is None:
        # Se não houver registros financeiros, retorne uma resposta vazia ou faça o tratamento necessário
        return render(request, 'home/estatisticas/estatisticas.html')
    
    # Verificar o último registro financeiro
    ultimo_financeiro = Chamado.objects.order_by('data_abertura').last()
    if ultimo_financeiro is None:
        # Se não houver registros financeiros, retorne uma resposta vazia ou faça o tratamento necessário
        return render(request, 'home/estatisticas/estatisticas.html')

    # Obter o ano e o mês do primeiro registro
    primeiro_ano = primeiro_financeiro.data_abertura.year
    primeiro_mes = primeiro_financeiro.data_abertura.month

    # Obter o ano e o mês do último registro
    ultimo_ano = ultimo_financeiro.data_abertura.year
    ultimo_mes = ultimo_financeiro.data_abertura.month
    
    dados_por_mes = {}

    # Loop pelos anos
    for ano in range(primeiro_ano, ultimo_ano + 1):
        # Determinar o mês inicial e final do loop baseado no ano
        mes_inicial = primeiro_mes if ano == primeiro_ano else 1
        mes_final = ultimo_mes if ano == ultimo_ano else 12

        # Loop pelos meses
        for mes in range(mes_inicial, mes_final + 1):
            # Calcular o primeiro e o último dia do mês
            primeiro_dia = timezone.make_aware(datetime(ano, mes, 1))
            ultimo_dia = timezone.make_aware(datetime(ano, mes, monthrange(ano, mes)[1], 23, 59, 59))

            # Filtrar os registros financeiros para o mês atual
            registros_do_mes = Chamado.objects.filter(
                data_abertura__gte=primeiro_dia,
                data_abertura__lt=ultimo_dia + timezone.timedelta(days=1),
                ativo=True
            )

            total_abertos = registros_do_mes.count()

            # Contar os chamados fechados no mês
            total_fechados = registros_do_mes.filter(Q(status=True) & Q(ativo=True)).count()  # Supondo que o status 'fechado' indica chamados fechados

            # Contar os chamados ainda abertos no mês
            total_em_aberto = registros_do_mes.filter(Q(status=False) & Q(ativo=True)).count()  # Supondo que o status 'aberto' indica chamados em aberto

            # Adicionar os dados ao dicionário
            if ano not in dados_por_mes:
                dados_por_mes[ano] = {}
            dados_por_mes[ano][mes] = {
                'total_abertos': total_abertos,
                'total_fechados': total_fechados,
                'total_em_aberto': total_em_aberto,
            }

    return dados_por_mes


def get_top_sectors_and_employees(request):
    # Top 3 setores que mais abrem chamados
    setores_mais_abrem_ids = Chamado.objects.values('setor').annotate(total_abertos=Count('id')).order_by('-total_abertos')[:3]
    setores_mais_abrem = [
        {
            'setor': Setor.objects.get(id=s['setor']),
            'total_abertos': s['total_abertos']
        }
        for s in setores_mais_abrem_ids
    ]
    
    # Top 3 setores que mais recebem chamados
    setores_mais_recebem_ids = Chamado.objects.values('setor').annotate(total_recebidos=Count('id')).order_by('-total_recebidos')[:3]
    setores_mais_recebem = [
        {
            'setor': Setor.objects.get(id=s['setor']),
            'total_recebidos': s['total_recebidos']
        }
        for s in setores_mais_recebem_ids
    ]
    
    # Top 3 funcionários que mais abrem chamados
    funcionarios_mais_abrem_ids = Chamado.objects.values('funcionario_abriu').annotate(total_abertos=Count('id')).order_by('-total_abertos')[:3]
    funcionarios_mais_abrem = [
        {
            'funcionario': Funcionario.objects.get(id=f['funcionario_abriu']),
            'total_abertos': f['total_abertos']
        }
        for f in funcionarios_mais_abrem_ids
    ]
    
    # Top 3 funcionários que mais fecham chamados
    funcionarios_mais_fecham_ids = Chamado.objects.filter(status=True).values('funcionario_fechou').annotate(total_fechados=Count('id')).order_by('-total_fechados')[:3]
    funcionarios_mais_fecham = [
        {
            'funcionario': Funcionario.objects.get(id=f['funcionario_fechou']),
            'total_fechados': f['total_fechados']
        }
        for f in funcionarios_mais_fecham_ids
    ]

    return {
        'setores_mais_abrem': setores_mais_abrem,
        'setores_mais_recebem': setores_mais_recebem,
        'funcionarios_mais_abrem': funcionarios_mais_abrem,
        'funcionarios_mais_fecham': funcionarios_mais_fecham,
    }

def estatisticas_view(request):
    dados_por_mes = get_dados_por_mes(request)
    top_dados = get_top_sectors_and_employees(request)

    setores_mais_abrem = json.dumps([(data["setor"].nome, data["total_abertos"]) for data in top_dados["setores_mais_abrem"]])
    setores_mais_recebem = json.dumps([(data["setor"].nome, data["total_recebidos"]) for data in top_dados["setores_mais_recebem"]])
    funcionarios_mais_abrem = json.dumps([(data["funcionario"].nome, data["total_abertos"]) for data in top_dados["funcionarios_mais_abrem"]])
    funcionarios_mais_fecham = json.dumps([(data["funcionario"].nome, data["total_fechados"]) for data in top_dados["funcionarios_mais_fecham"]])

    context = {
        'dados_por_mes': dados_por_mes,
        'top_setores_abrem': mark_safe(setores_mais_abrem),
        'top_setores_recebem': mark_safe(setores_mais_recebem),
        'top_funcionarios_abrem': mark_safe(funcionarios_mais_abrem),
        'top_funcionarios_fecham': mark_safe(funcionarios_mais_fecham),
    }

    return render(request, 'home/estatisticas/estatisticas.html', context)

home/views/home.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required

@login_required(login_url='login/')
def home_view(request):
    return render(request, 'home/home.html')

home/views/setor.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from ..models import setor
from ..forms import setorForm
from django.contrib.auth.decorators import login_required, permission_required
import logging

logger = logging.getLogger('main')

@login_required(login_url='/login/')
@permission_required('home.view_funcionario', raise_exception=True)
def setores_view(request):
    funcionario_usuario = request.user.perfil.funcionario
    setores = setor.objects.filter(status=True)
    return render(request, 'home/setores/setores.html', context={'setores': setores})

@login_required(login_url='/login/')
@permission_required('home.view_funcionario', raise_exception=True)
def adiciona_setor(request):
    home_usuario = request.user.perfil.home
    form = setorForm()
    
    if request.method == 'POST':
        form = setorForm(request.POST)
        if form.is_valid():
            setor = form.save(commit=False)
            setor.home = home_usuario 
            setor.save()
            logger.info(f'setor Criado | setor: {setor} | Usuário: {home_usuario}')
            return redirect('home:setores')
        else:
            form = setorForm()
            logger.warning(f'{form.errors}')
    return render(request, 'home/setores/adiciona_setor.html', context={'form': form})

@login_required(login_url='/login/')
@permission_required('home.view_funcionario', raise_exception=True)
def edita_setor(request, setor_id):
    home_usuario = request.user.perfil.home
    setor = get_object_or_404(setor, id=setor_id)

    if setor.home != home_usuario:
        raise Http404

    setor.tempo_necessario = str(setor.tempo_necessario).split(':')[-1]

    if request.method == 'POST':
        form = setorForm(request.POST, instance=setor)
        if form.is_valid():
            horario = form.save(commit=False)
            horario.home = home_usuario
            horario.save()
            logger.info(f'Horário de atendimento Editado | Horario Atendimento: {setor} | Usuário: {home_usuario}')
            return redirect('home:setores')
    else:
        form = setorForm(instance=setor)
    return render(request, 'home/setores/edita_setor.html', {'form': form, 'setor_id': setor_id})

@login_required(login_url='/login/')
@permission_required('home.view_funcionario', raise_exception=True)
def exclui_setor(request, setor_id):
    home_usuario = request.user.perfil.home
    setor = get_object_or_404(setor, pk=setor_id, home=home_usuario)

    if setor.home != home_usuario:
        raise Http404
    
    setor.delete()
    logger.info(f'Horário de atendimento excluido | Horario Atendimento: {setor} | Usuário: {home_usuario}')

    return redirect('home:setores')

home/templates/home/chamados/abrir_chamado.html
{% extends "base.html" %}
{% load static %}

{% block page_name %}Novo agendamento{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'home/css/chamados/editar_chamado.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    function redirecionarParaPagina() {
        window.location.href = '/chamados/';
    }
</script>
{% endblock %}

{% block content %}
<div class="card">
    
    <form action="{% url 'home:abrir_chamado' %}" method="POST">
        {% csrf_token %}
        <h1 class="titulo">Abrir chamado</h1>
        <p>
            <label>Descrição</label>
            <span id="spanDescricao">{{ form.descricao }}</span> 
        </p>
        <p>
            <label>Setor</label>
            {{ form.setor }}
        </p>
        {{form.errors}}
        <div class="button-container">
            <button type="button" class="cancela" onclick="redirecionarParaPagina();">Cancelar</button>
            <button type="submit" class="adiciona">Salvar</button>
        
        
        </div>
    </form>
</div>
{%endblock%}

home/templates/home/chamados/editar_chamado.html
{% extends "base.html" %}
{% load static %}

{% block page_name %}Editar Chamado{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'home/css/chamados/editar_chamado.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    function redirecionarParaPagina() {
        window.location.href = '/chamados/';
    }
</script>

<script>
    function redirecionarParaPaginaExcluir(agendamento_id) {
         window.location.href = '/chamado/deleta_chamado/' + agendamento_id + '/';
    }
</script>
{% endblock %}

{% block content %}
<div class="card">
    <form action="{% url 'home:edita_chamado' chamado.id %}" method="POST">
        {% csrf_token %}
        <h1 class="titulo">Chamado</h1>
        <p>
            <label>Descrição</label>
            {{ form.descricao }}
        </p>
        <p>
            <label>Funcionário que Abriu</label>
            {{ form.funcionario_abriu }}
        </p>
        <p>
            <label>Funcionário que Fechou</label>
            {{ form.funcionario_fechou }}
        </p>
        <p>
            <label>Setor Chamado</label>
            {{ form.setor }}
        </p>
        <p>
            <label>Descrição da Solução</label>
            {{ form.descricao_solucao }}
        </p>
        <p>
            <label>Data de Abertura</label>
            {{ form.data_abertura_display }}
        </p>
        <p>
            <label>Data de Fechamento</label>
            {{ form.data_fechamento_display }}
        </p>
        <p>
            <label>Status</label>
            {{ form.status }}
        </p>
        <div class="button-container">
            <button type="button" class="exclui" onclick="redirecionarParaPagina();">Cancelar</button>
            <button type="submit" class="edita">Editar</button>
            <button type="button" class="cancela" onclick="redirecionarParaPaginaExcluir({{ chamado.id }});">Excluir</button>
        </div>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('id_descricao_solucao').disabled = true;
        document.getElementById('id_status').disabled = true;
        document.getElementById('id_funcionario_fechou').disabled = true;
        document.getElementById('id_funcionario_abriu').disabled = true;

        if ('{{nivel_usuario}}' === 'adm_sistema') {
            document.getElementById('id_descricao_solucao').disabled = false;
            document.getElementById('id_status').disabled = false;
            document.getElementById('id_funcionario_fechou').disabled = false;
            document.getElementById('id_funcionario_abriu').disabled = false;
        }

        if ('{{nivel_usuario}}' === 'adm') {
            document.getElementById('id_funcionario_abriu').disabled = false;
        }
    });
</script>
{% endblock %}