home/urls.py
from django.urls import path
from .views import * 

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    
    path('chamados/', chamados_view, name='chamados_view'),
    path('chamado/edita_chamado/<int:chamado_id>/', edita_chamado, name='edita_chamado'),
    path('chamado/deleta_chamado/<int:chamado_id>/', deleta_chamado, name='deleta_chamado'),
    path('chamado/concluir_chamado/<int:chamado_id>/', concluir_chamado, name='concluir_chamado'),
    path('chamado/reabrir_chamado/<int:chamado_id>/', reabrir_chamado, name='reabrir_chamado'),
    path('chamados/abrir_chamado/', abrir_chamado, name='abrir_chamado'),
   
    path('funcionarios/', funcionarios_view, name='funcionarios'),
    path('funcionarios/edita_funcionario/<int:funcionario_id>/', edita_funcionario, name="edita_funcionario"),
    path('funcionarios/exclui_funcionario/<int:funcionario_id>/', exclui_funcionario, name="exclui_funcionario"),
    path('funcionarios/adiciona_funcionario/', adiciona_funcionario, name="adiciona_funcionario"),
    path('funcionarios/deleta_chamado_funcionario/<int:chamado_id>/', deleta_chamado_funcionario, name="deleta_chamado_funcionario"),
   
    path('estatisticas/', estatisticas_view, name='estatisticas'),

    # path('setores/', setores_view, name='setores'),
    # path('setores/adiciona_setor/', adiciona_setor, name='adiciona_setor'),
    # path('setores/edita_setor/<int:setor_id>/', edita_setor, name='edita_setor'),
    # path('setores/exclui_setor/<int:setor_id>/', exclui_setor, name='exclui_setor'),

    path('login/', login_view, name='login'),
    path("logout/", logout_view, name="logout"),
]

prefeitura/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import messages
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

prefeitura/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'prefeitura/css/base_style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script type="text/javascript" src="{% static 'prefeitura/js/base_js.js' %}"></script>
    <link rel="icon" href="{% static 'prefeitura/images/logo.ico' %}">
    {% block header %}
    {% endblock %}
    <title>{% block page_name %}{% endblock %}</title>
</head>
<body id="body-pd">
    <div class="header" id="header">
        <div class="header_toggle"> 
            <i class='bx bx-menu' id="header-toggle"></i> 
            <span class="usuario-salao" style="font-weight:600; font-size: 13px">{{ request.user.first_name }} | {{ request.user.perfil.funcionario.setor }}</span>
        </div>
    </div>
    <div class="container">
        <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div> <a href="{% url 'home:home' %}" class="nav_logo"> <i class="fa-solid fa-house"></i> <span class="nav_logo-name">CyberSolutions</a> 
                    <div class="nav_list"> 
                        <a href="{% url 'home:chamados_view' %}" class="nav_link"> 
                            <i class='bx bx-message-square-detail nav_icon'></i> 
                            <span class="nav_name">Chamados</span> 
                        </a> 
                        <a href="{% url 'home:funcionarios' %}" class="nav_link"> 
                            <i class='bx bxs-briefcase'></i>
                            <span class="nav_name">Funcionários</span> 
                        </a> 
                        <a href="{% url 'home:estatisticas' %}" class="nav_link"> 
                            <i class='bx bxs-bar-chart-alt-2' ></i>
                            <span class="nav_name">Estatísticas</span> 
                        </a> 
                        <a href="{% url 'home:logout' %}" class="nav_link"> 
                            <i class='bx bx-log-out nav_icon'></i> 
                            <span class="nav_name">Sair</span>
                        </a>
                    </div>
                </div> 
            </nav>
        </div>
        <div class="main_content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
        <!--Container Main end-->
</html>